import type { KnowledgeConcept, GlossaryTerm, KnowledgeCenterCategory } from './types';

export const knowledgeGraph: KnowledgeConcept[] = [
  {
    id: 'concept-operational-decision-intelligence',
    slug: 'operational-decision-intelligence',
    title: 'Operational Decision Intelligence',
    kind: 'concept',
    summary: 'Estrutura para traduzir investigação em decisões operacionais acionáveis.',
    description: 'Modelo conceitual para ligar evidência, hipóteses e decisão em uma cadeia rastreável.',
    relatedConceptIds: ['framework-ecf', 'framework-cef', 'component-cognitive-runtime'],
    frameworkIds: ['framework-ecf', 'framework-cef'],
    domainIds: ['domain-manufacturing'],
    references: ['ECF', 'CEF', 'Governor'],
  },
  {
    id: 'framework-ecf',
    slug: 'ecf',
    title: 'ECF',
    kind: 'framework',
    summary: 'Evidence Classification Framework.',
    description: 'Estrutura para categorizar evidência e orientar a evolução do estado investigativo.',
    relatedConceptIds: ['concept-operational-decision-intelligence', 'component-evidence-semantic-interpreter'],
    frameworkIds: [],
    domainIds: ['domain-manufacturing', 'domain-pharmaceutical'],
    references: ['Evidence', 'Hypothesis', 'Decision'],
  },
  {
    id: 'framework-cef',
    slug: 'cef',
    title: 'CEF',
    kind: 'framework',
    summary: 'Confidence Evidence Framework.',
    description: 'Estrutura para ligar confiança, evidência e recomendação operacional.',
    relatedConceptIds: ['concept-operational-decision-intelligence', 'component-evidence-acquisition-planner'],
    frameworkIds: [],
    domainIds: ['domain-manufacturing', 'domain-healthcare'],
    references: ['Evidence', 'Hypothesis', 'Decision'],
  },
  {
    id: 'component-cognitive-runtime',
    slug: 'cognitive-runtime',
    title: 'Cognitive Runtime',
    kind: 'component',
    summary: 'Motor cognitivo responsável por conduzir investigação adaptativa.',
    description: 'Componente central que orquestra interpretação, hipóteses, evidência e decisão.',
    relatedConceptIds: ['component-cognitive-investigation-engine', 'component-evidence-acquisition-planner'],
    frameworkIds: ['framework-ecf', 'framework-cef'],
    domainIds: ['domain-manufacturing'],
    references: ['Operational Object', 'Evidence', 'Hypothesis'],
  },
  {
    id: 'component-cognitive-investigation-engine',
    slug: 'cognitive-investigation-engine',
    title: 'Cognitive Investigation Engine',
    kind: 'component',
    summary: 'Motor de investigação adaptativa para perguntas e evolução do estado.',
    description: 'Componente que traduz respostas do usuário em evidência, hipóteses e progresso investigativo.',
    relatedConceptIds: ['component-cognitive-runtime', 'component-domain-expert-communication-layer'],
    frameworkIds: ['framework-ecf', 'framework-cef'],
    domainIds: ['domain-manufacturing'],
    references: ['Investigation', 'Evidence', 'Hypothesis'],
  },
  {
    id: 'component-evidence-semantic-interpreter',
    slug: 'evidence-semantic-interpreter',
    title: 'Evidence Semantic Interpreter',
    kind: 'component',
    summary: 'Interpretador semântico para inferir significado e lacunas a partir de evidência.',
    description: 'Componente responsável por associar semântica, contradição, validação e lacunas.',
    relatedConceptIds: ['framework-ecf', 'component-evidence-acquisition-planner'],
    frameworkIds: ['framework-ecf'],
    domainIds: ['domain-pharmaceutical'],
    references: ['Evidence', 'Hypothesis'],
  },
  {
    id: 'component-competitive-hypothesis-manager',
    slug: 'competitive-hypothesis-manager',
    title: 'Competitive Hypothesis Manager',
    kind: 'component',
    summary: 'Gerencia competição e dominância entre hipóteses concorrentes.',
    description: 'Componente que ordena hipóteses por força explicativa e reduz redundância.',
    relatedConceptIds: ['component-cognitive-investigation-engine', 'component-evidence-acquisition-planner'],
    frameworkIds: ['framework-cef'],
    domainIds: ['domain-quality'],
    references: ['Hypothesis', 'Decision'],
  },
  {
    id: 'component-evidence-acquisition-planner',
    slug: 'evidence-acquisition-planner',
    title: 'Evidence Acquisition Planner',
    kind: 'component',
    summary: 'Planeja aquisição de evidência por valor informacional.',
    description: 'Componente que prioriza perguntas e evidências com maior potencial de reduzir incerteza.',
    relatedConceptIds: ['component-cognitive-investigation-engine', 'component-domain-expert-communication-layer'],
    frameworkIds: ['framework-cef'],
    domainIds: ['domain-manufacturing', 'domain-healthcare'],
    references: ['Evidence', 'Investigation'],
  },
  {
    id: 'component-domain-expert-communication-layer',
    slug: 'domain-expert-communication-layer',
    title: 'Domain Expert Communication Layer',
    kind: 'component',
    summary: 'Camada de comunicação especializada para perguntas e justificativas.',
    description: 'Componente responsável por adaptar a linguagem da investigação ao domínio.',
    relatedConceptIds: ['component-evidence-acquisition-planner', 'component-cognitive-investigation-engine'],
    frameworkIds: ['framework-cef'],
    domainIds: ['domain-pharmaceutical', 'domain-healthcare', 'domain-finance'],
    references: ['Evidence', 'Hypothesis'],
  },
  {
    id: 'component-cognitive-memory-window',
    slug: 'cognitive-memory-window',
    title: 'Cognitive Memory Window',
    kind: 'component',
    summary: 'Controle de memória cognitiva para evitar perguntas redundantes.',
    description: 'Componente que limita repetição de questões e preserva foco investigativo.',
    relatedConceptIds: ['component-cognitive-investigation-engine'],
    frameworkIds: ['framework-cef'],
    domainIds: ['domain-cybersecurity'],
    references: ['Investigation', 'Evidence'],
  },
  {
    id: 'domain-manufacturing',
    slug: 'manufacturing',
    title: 'Manufacturing',
    kind: 'domain',
    summary: 'Domínio operacional para investigação aplicada em manufatura.',
    description: 'Domínio dedicado a processos, qualidade e rastreabilidade operacional.',
    relatedConceptIds: ['component-cognitive-runtime', 'framework-ecf'],
    frameworkIds: ['framework-ecf', 'framework-cef'],
    domainIds: [],
    references: ['Quality', 'Evidence'],
  },
  {
    id: 'domain-pharmaceutical',
    slug: 'pharmaceutical',
    title: 'Pharmaceutical',
    kind: 'domain',
    summary: 'Domínio regulatório e científico para validação de hipóteses.',
    description: 'Domínio preparado para investigação com rigor regulatório e validação experimental.',
    relatedConceptIds: ['component-evidence-semantic-interpreter', 'component-domain-expert-communication-layer'],
    frameworkIds: ['framework-ecf'],
    domainIds: [],
    references: ['Evidence', 'Hypothesis'],
  },
  {
    id: 'domain-healthcare',
    slug: 'healthcare',
    title: 'Healthcare',
    kind: 'domain',
    summary: 'Domínio para investigação clínica e operacional.',
    description: 'Domínio orientado à segurança, evidência e tomada de decisão em saúde.',
    relatedConceptIds: ['component-domain-expert-communication-layer', 'framework-cef'],
    frameworkIds: ['framework-cef'],
    domainIds: [],
    references: ['Evidence', 'Decision'],
  },
  {
    id: 'domain-cybersecurity',
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    kind: 'domain',
    summary: 'Domínio para investigação de segurança e incident response.',
    description: 'Domínio voltado a evidência, hipóteses e decisão em cenários de risco.',
    relatedConceptIds: ['component-cognitive-memory-window'],
    frameworkIds: ['framework-cef'],
    domainIds: [],
    references: ['Evidence', 'Hypothesis'],
  },
  {
    id: 'domain-finance',
    slug: 'finance',
    title: 'Finance',
    kind: 'domain',
    summary: 'Domínio para análise de risco e decisão financeira.',
    description: 'Domínio voltado a evidência, confiança e decisão em cenários financeiros.',
    relatedConceptIds: ['component-domain-expert-communication-layer'],
    frameworkIds: ['framework-cef'],
    domainIds: [],
    references: ['Decision', 'Evidence'],
  },
  {
    id: 'domain-quality',
    slug: 'quality',
    title: 'Quality',
    kind: 'domain',
    summary: 'Domínio de garantia de qualidade e melhoria contínua.',
    description: 'Domínio orientado à cobertura de evidência e consolidação de hipóteses.',
    relatedConceptIds: ['component-competitive-hypothesis-manager'],
    frameworkIds: ['framework-ecf', 'framework-cef'],
    domainIds: [],
    references: ['Evidence', 'Hypothesis'],
  },
];

export const glossaryTerms: GlossaryTerm[] = [
  {
    id: 'term-operational-decision-intelligence',
    slug: 'operational-decision-intelligence',
    term: 'Operational Decision Intelligence',
    definition: 'Camada operacional para traduzir investigação cognitiva em decisão ação.',
    shortDescription: 'Conecta investigação, evidência e decisão.',
    fullDescription: 'Representa a disciplina de tornar o resultado do runtime cognitivo acionável para operação e governança.',
    usageContext: 'Usado para descrever o objetivo final da investigação e da tomada de decisão.',
    relatedTerms: ['Cognitive Runtime', 'Evidence', 'Hypothesis', 'Decision'],
    synonyms: ['ODI'],
    deprecatedTerms: [],
  },
  {
    id: 'term-cognitive-runtime',
    slug: 'cognitive-runtime',
    term: 'Cognitive Runtime',
    definition: 'Motor de investigação adaptativa responsável por conduzir o ciclo de problema, hipótese, evidência e decisão.',
    shortDescription: 'Motor cognitivo central da plataforma.',
    fullDescription: 'É a camada responsável por coordenar os componentes que interpretam problemas, geram hipóteses, avaliam evidências e recomendam decisões.',
    usageContext: 'Usado para referenciar a arquitetura operacional da ATLAZ.',
    relatedTerms: ['Operational Object', 'Evidence', 'Hypothesis', 'Cognitive Investigation Engine'],
    synonyms: ['Runtime Cognitivo'],
    deprecatedTerms: [],
  },
  {
    id: 'term-operational-object',
    slug: 'operational-object',
    term: 'Operational Object',
    definition: 'Estrutura semântica inicial que representa o problema, contexto e requisitos de informação.',
    shortDescription: 'Entrada inicial do runtime.',
    fullDescription: 'É o artefato inicial que encapsula a interpretação inicial do problema e o que precisa ser investigado.',
    usageContext: 'Usado no início do fluxo para estruturar a investigação.',
    relatedTerms: ['Cognitive Runtime', 'Evidence', 'Hypothesis'],
    synonyms: ['Objeto Operacional'],
    deprecatedTerms: [],
  },
  {
    id: 'term-evidence',
    slug: 'evidence',
    term: 'Evidence',
    definition: 'Registro de uma observação, resposta ou artefato que altera a confiança de uma hipótese.',
    shortDescription: 'Base de suporte ou contradição.',
    fullDescription: 'A evidência é o principal insumo para evoluir o estado da investigação e para decidir se a hipótese deve avançar ou ser rejeitada.',
    usageContext: 'Usado para descrever qualquer dado ou sinal relevante para a investigação.',
    relatedTerms: ['Hypothesis', 'ECF', 'CEF'],
    synonyms: ['Evidência'],
    deprecatedTerms: [],
  },
  {
    id: 'term-hypothesis',
    slug: 'hypothesis',
    term: 'Hypothesis',
    definition: 'Explicação plausível para um fenômeno que será testada por evidência.',
    shortDescription: 'Hipótese investigativa.',
    fullDescription: 'As hipóteses são comparadas por coerência causal, confiança e suporte evidencial.',
    usageContext: 'Usado para referenciar explicações candidatas durante a investigação.',
    relatedTerms: ['Evidence', 'Decision'],
    synonyms: ['Hipótese'],
    deprecatedTerms: [],
  },
  {
    id: 'term-ecf',
    slug: 'ecf',
    term: 'ECF',
    definition: 'Evidence Classification Framework.',
    shortDescription: 'Estrutura de classificação de evidências.',
    fullDescription: 'Classifica evidências por categoria, tipo e relação com hipóteses.',
    usageContext: 'Usado para organizar evidência e governança de lifecycle.',
    relatedTerms: ['CEF', 'Evidence', 'Governor'],
    synonyms: ['Framework de Classificação de Evidência'],
    deprecatedTerms: [],
  },
  {
    id: 'term-cef',
    slug: 'cef',
    term: 'CEF',
    definition: 'Confidence Evidence Framework.',
    shortDescription: 'Estrutura de confiança e evidência.',
    fullDescription: 'Liga evidência e confiança para orientar a evolução da hipótese e da decisão.',
    usageContext: 'Usado para referenciar o mecanismo de avaliação de confiança.',
    relatedTerms: ['ECF', 'Evidence', 'Hypothesis'],
    synonyms: ['Framework de Confiança'],
    deprecatedTerms: [],
  },
  {
    id: 'term-governor',
    slug: 'governor',
    term: 'Governor',
    definition: 'Camada de governança que impede transições inválidas de lifecycle.',
    shortDescription: 'Governança de transição.',
    fullDescription: 'Aplica regras de integridade para garantir que a evolução de hipótese e decisão permaneça coerente.',
    usageContext: 'Usado em contextos de validação e integridade.',
    relatedTerms: ['ECF', 'CEF', 'Decision'],
    synonyms: ['Governança'],
    deprecatedTerms: [],
  },
  {
    id: 'term-explainability',
    slug: 'explainability',
    term: 'Explainability',
    definition: 'Capacidade de explicar por que uma pergunta, hipótese ou recomendação foi produzida.',
    shortDescription: 'Rastreabilidade cognitiva.',
    fullDescription: 'É a camada que torna o processo investigativo explícito para usuários, governança e análise.',
    usageContext: 'Usado para descrever transparência operacional do runtime.',
    relatedTerms: ['Cognitive Runtime', 'Evidence', 'Decision'],
    synonyms: ['Explicabilidade'],
    deprecatedTerms: [],
  },
  {
    id: 'term-evidence-semantic-interpreter',
    slug: 'evidence-semantic-interpreter',
    term: 'Evidence Semantic Interpreter',
    definition: 'Componente que interpreta o significado semântico de evidência e resposta.',
    shortDescription: 'Interpretação semântica de evidência.',
    fullDescription: 'Detecta estrutura de suporte, contradição, lacuna e necessidade de validação.',
    usageContext: 'Usado para descrever o módulo de semântica da investigação.',
    relatedTerms: ['Evidence', 'Hypothesis', 'ECF'],
    synonyms: ['Interpretador Semântico'],
    deprecatedTerms: [],
  },
  {
    id: 'term-competitive-hypothesis-manager',
    slug: 'competitive-hypothesis-manager',
    term: 'Competitive Hypothesis Manager',
    definition: 'Módulo que gerencia competição entre hipóteses concorrentes.',
    shortDescription: 'Competição entre hipóteses.',
    fullDescription: 'Acompanha domínio, redundância e prioridade entre hipóteses em evolução.',
    usageContext: 'Usado para descrever a gestão de múltiplas hipóteses.',
    relatedTerms: ['Hypothesis', 'Decision'],
    synonyms: ['Gestor de Hipóteses Concorrentes'],
    deprecatedTerms: [],
  },
  {
    id: 'term-evidence-acquisition-planner',
    slug: 'evidence-acquisition-planner',
    term: 'Evidence Acquisition Planner',
    definition: 'Módulo que prioriza a aquisição de evidência por valor informacional.',
    shortDescription: 'Planejamento de coleta de evidência.',
    fullDescription: 'Avalia o ganho esperado de informação e orienta a próxima pergunta ou evidência a ser coletada.',
    usageContext: 'Usado para descrever a estratégia de coleta de evidência.',
    relatedTerms: ['Evidence', 'Cognitive Investigation Engine'],
    synonyms: ['Planejador de Aquisição'],
    deprecatedTerms: [],
  },
  {
    id: 'term-domain-expert-communication-layer',
    slug: 'domain-expert-communication-layer',
    term: 'Domain Expert Communication Layer',
    definition: 'Camada que adapta a comunicação da investigação para o domínio do problema.',
    shortDescription: 'Linguagem especializada.',
    fullDescription: 'Ajuda a produzir perguntas mais naturais e autênticas para a área de aplicação.',
    usageContext: 'Usado para descrever comunicação especializada do runtime.',
    relatedTerms: ['Evidence', 'Hypothesis'],
    synonyms: ['Camada de Comunicação Especializada'],
    deprecatedTerms: [],
  },
  {
    id: 'term-cognitive-memory-window',
    slug: 'cognitive-memory-window',
    term: 'Cognitive Memory Window',
    definition: 'Mecanismo de memória que impede repetição indevida de perguntas e preserva foco.',
    shortDescription: 'Memória para evitar redundância.',
    fullDescription: 'Controla o histórico cognitivo para reduzir redundância e melhorar a qualidade investigativa.',
    usageContext: 'Usado para descrever a gestão de histórico de perguntas e evidência.',
    relatedTerms: ['Cognitive Runtime', 'Evidence'],
    synonyms: ['Janela de Memória Cognitiva'],
    deprecatedTerms: [],
  },
  {
    id: 'term-cognitive-investigation-engine',
    slug: 'cognitive-investigation-engine',
    term: 'Cognitive Investigation Engine',
    definition: 'Motor responsável por conduzir a investigação adaptativa com base em hipóteses e evidência.',
    shortDescription: 'Motor da investigação.',
    fullDescription: 'Coordena o ciclo da pergunta, resposta, estudo das hipóteses e evolução do estado investigativo.',
    usageContext: 'Usado para descrever a execução da investigação.',
    relatedTerms: ['Cognitive Runtime', 'Evidence', 'Hypothesis'],
    synonyms: ['Motor de Investigação Cognitiva'],
    deprecatedTerms: [],
  },
];

export const knowledgeCenterCategories: KnowledgeCenterCategory[] = [
  {
    id: 'category-cognitive-engineering',
    slug: 'cognitive-engineering',
    title: 'Cognitive Engineering',
    description: 'Princípios e arquiteturas para construção do runtime cognitivo.',
    featuredConceptIds: ['component-cognitive-runtime', 'component-cognitive-investigation-engine'],
  },
  {
    id: 'category-root-cause-analysis',
    slug: 'root-cause-analysis',
    title: 'Root Cause Analysis',
    description: 'Estratégias para investigar causas profundas e reduzir recorrência.',
    featuredConceptIds: ['component-evidence-semantic-interpreter', 'component-competitive-hypothesis-manager'],
  },
  {
    id: 'category-evidence-governance',
    slug: 'evidence-governance',
    title: 'Evidence Governance',
    description: 'Governança, validação e rastreabilidade das evidências.',
    featuredConceptIds: ['framework-ecf', 'framework-cef'],
  },
  {
    id: 'category-decision-intelligence',
    slug: 'decision-intelligence',
    title: 'Decision Intelligence',
    description: 'Técnicas para transformar evidência em decisão acionável.',
    featuredConceptIds: ['concept-operational-decision-intelligence', 'component-evidence-acquisition-planner'],
  },
  {
    id: 'category-manufacturing',
    slug: 'manufacturing',
    title: 'Manufacturing',
    description: 'Aplicações da investigação cognitiva em manufatura.',
    featuredConceptIds: ['domain-manufacturing'],
  },
  {
    id: 'category-pharmaceutical',
    slug: 'pharmaceutical',
    title: 'Pharmaceutical',
    description: 'Aplicações de alto rigor regulatório e validation-driven.',
    featuredConceptIds: ['domain-pharmaceutical'],
  },
  {
    id: 'category-healthcare',
    slug: 'healthcare',
    title: 'Healthcare',
    description: 'Investigação contextual e operacional em saúde.',
    featuredConceptIds: ['domain-healthcare'],
  },
  {
    id: 'category-cybersecurity',
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    description: 'Investigação orientada a risco e incident response.',
    featuredConceptIds: ['domain-cybersecurity'],
  },
  {
    id: 'category-finance',
    slug: 'finance',
    title: 'Finance',
    description: 'Aplicações em risco, decisão e evidência financeira.',
    featuredConceptIds: ['domain-finance'],
  },
  {
    id: 'category-quality',
    slug: 'quality',
    title: 'Quality',
    description: 'Aplicações em garantia de qualidade e melhoria contínua.',
    featuredConceptIds: ['domain-quality'],
  },
  {
    id: 'category-ai',
    slug: 'ai',
    title: 'AI',
    description: 'Estratégias de preparação para IA generativa e descoberta semântica.',
    featuredConceptIds: ['component-cognitive-runtime', 'component-evidence-semantic-interpreter'],
  },
];
